name: CI

on:
  # Triggers the workflow on push event but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  JAVA_DISTRIBUTION: 'temurin'
  MAX_JAVA_VERSION: 17

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: 17
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK ${{ env.MAX_JAVA_VERSION }}
        uses: actions/setup-java@v4.2.1
        with:
          java-version: ${{ env.MAX_JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Check api
        run: ./gradlew apiCheck --no-daemon

      - name: Detekt
        run: ./gradlew detekt --no-daemon

      - name: Sonar
        run: ./gradlew test koverXmlReport sonar --no-daemon

  build:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        version: [ 1.8 ]
        target: [
          { arch: x64, os: ubuntu-latest },
        ]
    runs-on: ${{ matrix.target.os }}
    needs: check
    env:
      JAVA_VERSION: ${{ matrix.version }}
    name: Build with JDK ${{ matrix.version }} ${{ matrix.target.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK ${{ env.MAX_JAVA_VERSION }}
        uses: actions/setup-java@v4.2.1
        with:
          java-version: ${{ env.MAX_JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          architecture: ${{ matrix.target.arch }}

      - name: Restore Gradle Cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build
        continue-on-error: false
        run: ./gradlew build -x detekt --no-daemon

      - name: Save workspace
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}
          key: |
            build-${{github.sha}}-${{ matrix.version }}-${{matrix.target.arch}}

  publish:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        version: [ 1.8 ]
        target: [
          { arch: x64, os: ubuntu-latest },
        ]
    runs-on: ${{ matrix.target.os }}
    needs: build
    env:
      JAVA_VERSION: ${{ matrix.version }}
    steps:
      - name: Setup JDK ${{ env.MAX_JAVA_VERSION }}
        uses: actions/setup-java@v4.2.1
        with:
          java-version: ${{ env.MAX_JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          architecture: ${{ matrix.target.arch }}

      - name: Restore Gradle Cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Restore Workspace
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}
          key: |
            build-${{github.sha}}-${{ matrix.version }}-${{matrix.target.arch}}
          fail-on-cache-miss: true

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish
        env:
          REPOSITORY_SNAPSHOTS_URL: ${{ secrets.REPOSITORY_SNAPSHOTS_URL }}
          REPOSITORY_RELEASES_URL: ${{ secrets.REPOSITORY_RELEASES_URL }}
          REPOSITORY_USERNAME: ${{ secrets.REPOSITORY_USERNAME }}
          REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: false
        run: ./gradlew publish -x detekt --no-daemon
