name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check api
        run: ./gradlew apiCheck

      - name: Generate kover coverage report
        run: ./gradlew koverXmlReport

  build:
    strategy:
      max-parallel: 1
      matrix:
        version: [ 1.8, 17, 21 ]
    runs-on: ubuntu-latest
    needs: check
    env:
      JAVA_VERSION: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        continue-on-error: false
        run: ./gradlew build
