name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      MAX_JAVA_VERSION: 17
      JAVA_VERSION: 17
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK ${{ env.MAX_JAVA_VERSION }}
        uses: actions/setup-java@v4.2.1
        with:
          java-version: ${{ env.MAX_JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check api
        run: ./gradlew apiCheck --no-daemon

      - name: Detekt
        run: ./gradlew apiCheck --no-daemon

      - name: Generate kover coverage report
        run: ./gradlew koverXmlReport --no-daemon

  build:
    strategy:
      max-parallel: 1
      matrix:
        version: [ 1.8 ]
        target: [
          { arch: x64, os: ubuntu-latest },
        ]
    runs-on: ubuntu-latest
    needs: check
    env:
      MAX_JAVA_VERSION: 17
      JAVA_VERSION: ${{ matrix.version }}
    name: Build with JDK ${{ matrix.version }} ${{ matrix.target.arch }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK ${{ env.MAX_JAVA_VERSION }}
        uses: actions/setup-java@v4.2.1
        with:
          java-version: ${{ env.MAX_JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          architecture: ${{ matrix.target.arch }}

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        continue-on-error: false
        run: ./gradlew build -x detekt --no-daemon
