name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MAX_JDK: '17'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: $MAX_JDK
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK $MAX_JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: $MAX_JDK
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check api
        run: ./gradlew apiCheck

      - name: Generate kover coverage report
        run: ./gradlew koverXmlReport

  build:
    strategy:
      max-parallel: 1
      matrix:
        version: [ 1.8 ]
        arch: [ x64, arm64 ]
    runs-on: ubuntu-latest
    needs: check
    env:
      JAVA_VERSION: ${{ matrix.version }}
    name: Build with JDK ${{ matrix.version }} ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK $MAX_JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: $MAX_JDK
          distribution: 'temurin'
          architecture: ${{ matrix.arch }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        continue-on-error: false
        run: ./gradlew build
